name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup DynamoDB
      uses: rrainn/dynamodb-action@v2.0.0
      with:
        port: 8000
        cors: '*'
        sharedDb: true
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Prepare Test Config
      run: 'cd testhelper/assets && echo "$CONFIG" > config.json'
      shell: bash
      env:
        CONFIG: ${{ secrets.TEST_CONFIG }}
    - name: Build
      run: make build
    
    - name: Test
      run: make test
      env:
        AWS_REGION: 'eu-central-1'
        AWS_ACCESS_KEY_ID: 'key'
        AWS_SECRET_ACCESS_KEY: 'secret'
